apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-gateway-ext-proc
  namespace: team1
  labels:
    app: inference-gateway-ext-proc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference-gateway-ext-proc
  template:
    metadata:
      labels:
        app: inference-gateway-ext-proc
    spec:
      initContainers:
      - name: config-writer
        image: busybox:1.36
        command:
        - "sh"
        - "-c"
        - |
          cat <<'EOF' > /config/default-plugins.yaml
              apiVersion: inference.networking.x-k8s.io/v1alpha1
              kind: EndpointPickerConfig
              plugins:
              - type: queue-scorer
              - type: kv-cache-utilization-scorer
              - type: prefix-cache-scorer
              schedulingProfiles:
              - name: default
                plugins:
                - pluginRef: queue-scorer
                - pluginRef: kv-cache-utilization-scorer
                - pluginRef: prefix-cache-scorer
          EOF
        volumeMounts:
        - name: plugins-config-volume
          mountPath: "/config"
      nodeSelector:
        node.kubernetes.io/instance-type: n2-standard-16
      containers:
      - name: inference-gateway-ext-proc
        image: registry.k8s.io/gateway-api-inference-extension/epp:v1.0.0-rc.1
        #image: registry.k8s.io/gateway-api-inference-extension/epp:v0.5.1
        imagePullPolicy: Always
        args:
        - --pool-name
        - "test-inference-pool"
        - --pool-namespace
        - "team1"
        - --pool-group
        - "inference.networking.x-k8s.io"
        - -v
        - "1"
        - --zap-encoder
        - "json"
        - --grpc-port
        - "9002"
        - --grpc-health-port
        - "9003"
        - "--config-file"
        - "/config/default-plugins.yaml"
        - "--enable-pprof=true"
        ports:
        - containerPort: 9002
        - containerPort: 9003
        - name: metrics
          containerPort: 9090
        livenessProbe:
          grpc:
            port: 9003
            service: inference-extension
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          grpc:
            port: 9003
            service: inference-extension
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: plugins-config-volume
          mountPath: "/config"
      volumes:
      - name: plugins-config-volume
        emptyDir: {}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-read
rules:
- apiGroups: ["inference.networking.x-k8s.io"]
  resources: ["inferencepools"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["inference.networking.x-k8s.io"]
  resources: ["inferenceobjectives"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create